[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
tests = ["test"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
